# Site settings
title: GPDB Rocks! Now becomes greenplum.cn!
description: > # this means to ignore newlines until "baseurl:"
  Everything about GPDB
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gpdb.rocks" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
